# Generated by Django 4.2.1 on 2023-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_timestamp_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
